version: '3.9'
services:
  webapp:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: webapp
  api:
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    container_name: api
    depends_on:
      - postgres
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    container_name: database
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:5050
    depends_on:
      - db
    env_file:
      - .env
    container_name: pgadmin

volumes:
  postgres-db: