version: '3.9'
services:
  backend-tests:
    build: ./backend
    ports:
      - 8080:80
    environment:
      - PROJECT_NAME
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - TEST_USER
      - TEST_USER_PASSWORD
      - ALGORITHM
    container_name: backend-tests
    command: bash && cd app/app && python app/pre_start.py && alembic upgrade head && python app/initial_data.py
