version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: frontend
    command: node server.js

  backend:
    build: ./backend
    ports:
      - 8000:80
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    container_name: backend
    command: /start-reload.sh
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: database

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:5050
    depends_on:
      - postgres
    env_file:
      - .env
    container_name: pgadmin

volumes:
  postgres-db:
