version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - 8000:80
    env_file:
      - .env
    container_name: backend
    command: /start.sh
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data-test
    container_name: database

volumes:
  postgres-db:
