version: '3.9'
services:
  webapp:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: webapp
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - 8000:8000
    # volumes:
    #   - ./:/app
    # env_file:
    #   - ./.env
    container_name: api
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=test123
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres-db:/var/lib/postgresql/data
    container_name: database

volumes:
  postgres-db: