version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - 8000:80
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    container_name: backend
    command: /start-reload.sh
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: database

volumes:
  postgres-db:
