version: '3.9'
services:
  webapp:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: webapp
    command: node server.js

  api:
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - .env
    container_name: api
    command: bash -c "./prestart.sh && uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: database

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:5050
    depends_on:
      - db
    env_file:
      - .env
    container_name: pgadmin

volumes:
  postgres-db:
