name: Cypress

on:
  push:
    branches: [ main ]
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
  pull_request:
    branches: [ main ]
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'

env:
  working-directory: ./frontend
      
jobs:
  cross-browser:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Cypress on Chrome
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        start: npm run dev
        config-file: cypress.json
        working-directory: ${{ env.working-directory }}
    - name: Run Cypress on Firefox
      uses: cypress-io/github-action@v2
      with:
        browser: firefox
        start: npm run dev
        config-file: cypress.json
        working-directory: ${{ env.working-directory }}
        
  edge:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Cypress on Edge
        uses: cypress-io/github-action@v2
        with: 
          browser: edge
          start-windows: npm run dev:windows:server
          config-file: cypress.json
          working-directory: ${{ env.working-directory }}
