name: Cypress

on:
  push:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
  pull_request:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'

env:
  working-directory: ./frontend
      
jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Run Cypress on Chrome
        uses: cypress-io/github-action@v2
        with: 
          browser: chrome
          build: npm run build
          start: npm run start
          config-file: cypress.json
          working-directory: ${{ env.working-directory }}
          
  firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Run Cypress on Firefox
        uses: cypress-io/github-action@v2
        with: 
          browser: firefox
          build: npm run build
          start: npm run start
          config-file: cypress.json
          working-directory: ${{ env.working-directory }}
        
  edge:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Run Cypress on Edge
        uses: cypress-io/github-action@v2
        with: 
          browser: edge
          build: npm run build
          start: npm run start
          config-file: cypress.json
          working-directory: ${{ env.working-directory }}
