name: Pytest

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Connect to PostgreSQL
      working-directory: ./backend/app/app
      run: |
        python pre_start.py
        alembic upgrade head
        python initial_data.py
      env:
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        TEST_USER: ${{ secrets.TEST_USER }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        ALGORITHM: ${{ secrets.ALGORITHM }}
    - name: Run Pytest
      run: pytest ./backend/app/tests/
      env:
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        TEST_USER: ${{ secrets.TEST_USER }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        ALGORITHM: ${{ secrets.ALGORITHM }}
